import { Router } from "express";
import authRouter from "../modules/auth";
import chapterAudiosRouter from "../modules/chapter-audios";
import chapterPurchasesRouter from "../modules/chapter-purchases";
import chaptersRouter from "../modules/chapters";
import commentsRouter from "../modules/comments";
import creatorEarningsRouter from "../modules/creator-earnings";
import creatorPayoutAccountsRouter from "../modules/creator-payout-accounts";
import notificationsRouter from "../modules/notifications";
import novelModerationLogsRouter from "../modules/novel-moderation-logs";
import novelPackagesRouter from "../modules/novel-packages";
import novelsRouter from "../modules/novels";
import packageItemsRouter from "../modules/package-items";
import packagePurchasesRouter from "../modules/package-purchases";
import paymentLogsRouter from "../modules/payment-logs";
import payoutRequestsRouter from "../modules/payout-requests";
import payoutsRouter from "../modules/payouts";
import readingLibraryRouter from "../modules/reading-library";
import topupTransactionsRouter from "../modules/topup-transactions";
import userReportsRouter from "../modules/user-reports";
import userRolesRouter from "../modules/user-roles";
import userSocialsRouter from "../modules/user-socials";
import usersRouter from "../modules/users";
import walletLedgerRouter from "../modules/wallet-ledger";
import workflowsRouter from "../modules/workflows";
import healthRouter from "./health.route";

const router = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/user-roles", userRolesRouter);
router.use("/user-socials", userSocialsRouter);
router.use("/novels", novelsRouter);
router.use("/chapters", chaptersRouter);
router.use("/chapter-audios", chapterAudiosRouter);
router.use("/novel-packages", novelPackagesRouter);
router.use("/package-items", packageItemsRouter);
router.use("/reading-library", readingLibraryRouter);
router.use("/topup-transactions", topupTransactionsRouter);
router.use("/payment-logs", paymentLogsRouter);
router.use("/wallet-ledger", walletLedgerRouter);
router.use("/package-purchases", packagePurchasesRouter);
router.use("/chapter-purchases", chapterPurchasesRouter);
router.use("/creator-earnings", creatorEarningsRouter);
router.use("/payout-requests", payoutRequestsRouter);
router.use("/payouts", payoutsRouter);
router.use("/novel-moderation-logs", novelModerationLogsRouter);
router.use("/comments", commentsRouter);
router.use("/notifications", notificationsRouter);
router.use("/user-reports", userReportsRouter);
router.use("/creator-payout-accounts", creatorPayoutAccountsRouter);
router.use("/workflows", workflowsRouter);

export default router;
